language: node_js
dist: xenial
node_js:
  - "10"
cache:
  yarn: true

addons:
  chrome: stable
  firefox: latest

branches:
  only:
    - master
    - release

# upgrade yarn to a more recent version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - name: "Test"
      script: |
        set -ex
        npx ts-mocha -r tsconfig-paths/register ./test/*.ts
        yarn run tslint
        yarn run prettier
        yarn run build-tests
        npx ts-mocha -r tsconfig-paths/register ./@here/*/test/*.ts
        yarn test-browser --headless-firefox
        yarn test-browser --headless-chrome
        ./scripts/test-npm-packages.sh
        git status # just in case test-npm-packages leaves some garbage
    - name: "Build & Deploy"
      script: |
        set -ex
        yarn run build
        yarn run typedoc
        echo -e 'include:\n  - "_*"' > dist/_config.yml
      deploy:
        - provider: script
          script: ./scripts/publish-packages.sh
          skip_cleanup: true
          on:
            branch: release
        - provider: pages
          skip_cleanup: true
          committer-from-gh: true
          keep-history: false
          local-dir: dist
          github-token: $GITHUB_TOKEN
          on:
            branch: release
