language: node_js
dist: bionic
node_js:
  - '10'
cache:
  yarn: true

addons:
  chrome: stable
  firefox: latest

branches:
  only:
    - master
    - release

env:
  - DETECT_CHROMEDRIVER_VERSION=true

before_install:
  - openssl aes-256-cbc -K $encrypted_0c7f5347a2b0_key -iv $encrypted_0c7f5347a2b0_iv -in git_deploy_key.enc -out git_deploy_key -d
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add codecov
  - chmod 600 git_deploy_key
  - eval "$(ssh-agent -s)"
  - ssh-add git_deploy_key

jobs:
  include:
    - name: Test
      script:
        - set -ex
        - yarn
        # - yarn pre-test
        # - yarn cov-test --forbid-only
        - yarn build-tests
        # - yarn test --headless-chrome
        - yarn get-reference-images-rendering-tests
        - yarn test-rendering-tests --headless-chrome
        - git status

    - name: Build & Deploy
      script:
        - cross-env NODE_ENV=production yarn run build
        - yarn run typedoc
        - cross-env NODE_ENV=production yarn run build-www
        - yarn prepare-doc-deploy
        - "./scripts/git-check-clean-workspace.sh"
      deploy:
        - provider: script
          script: "./scripts/publish-packages.sh"
          skip_cleanup: true
          on:
            branch: release
        - provider: pages
          skip_cleanup: true
          committer-from-gh: true
          keep-history: false
          local-dir: dist/gh_deploy
          github-token: "$GITHUB_TOKEN"
          on:
            branch: release
        - provider: s3
          access_key_id: "$AWS_ACCESS_KEY_ID"
          secret_access_key: "$AWS_SECRET_ACCESS_KEY"
          bucket: harp.gl
          skip_cleanup: true
          local_dir: dist/s3_deploy
          upload-dir: docs
          region: us-east-1
          acl: public_read
          cache_control: no-cache
          on:
            all_branches: true
            condition: "$TRAVIS_BRANCH =~ ^master|release$"

after_success:
  - codecov -f coverage/*.json
